# pipenv install fails if the python version is 12 or higher
FROM quay.io/qiime2/tiny:2024.5

ARG USERNAME=devuser
ARG USER_UID=1000
ARG USER_GID=${USER_UID}

# Create the user
# https://code.visualstudio.com/remote/advancedcontainers/add-nonroot-user#_creating-a-nonroot-user
RUN groupadd --gid ${USER_GID} ${USERNAME} \
    && useradd --uid ${USER_UID} --gid ${USER_GID} -m ${USERNAME} \
    && apt update \
    && apt upgrade -y \
    && apt install -y \
        sudo \
        git \
        zsh \
    && echo ${USERNAME} ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/${USERNAME} \
    && chmod 0440 /etc/sudoers.d/${USERNAME}

RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

# Process Substitution is only available in bash
SHELL ["/bin/bash", "-c"]
RUN source activate qiime2-tiny-2024.5 && \
    conda install \
        fastapi \
        uvicorn

# Install oh-my-zsh

CMD sleep infinity